spring:
  application:
    name: rococo-userdata
  main:
    web-application-type: none
  datasource:
    hikari:
      connection-timeout: 20000
      minimum-idle: 10
      maximum-pool-size: 30
      idle-timeout: 10000
      max-lifetime: 1000
      auto-commit: true
  flyway:
    enabled: true
    baseline-version: 0
    baseline-on-migrate: true
    schemas: rococo-userdata
    user: root
    password: secret
    locations: classpath:db/migration/rococo-userdata
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
    generate-ddl: true
    open-in-view: false
  grpc:
    server:
      servlet:
        enabled: false
grpc:
  server:
    port: 9090
logging:
  file:
    path: ./logs/rococo-userdata
  level:
    root: INFO
    org.springframework.kafka: INFO
    org.springframework.web: INFO
    org.springframework.boot.autoconfigure: INFO
---
spring:
  config:
    activate:
      on-profile: 'local'
  datasource:
    url: "jdbc:mysql://localhost:3307/rococo-userdata?useSSL=false&allowPublicKeyRetrieval=true"
    username: root
    password: secret
    driver-class-name: com.mysql.cj.jdbc.Driver
  kafka:
    bootstrap-servers: 'localhost:9092'
    consumer:
      group-id: 'userdata'
      auto-offset-reset: earliest