server:
  port: 8080

spring:
  application:
    name: rococo-gateway
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
    disable-swagger-default-url: true
    api-docs:
      path: /v3/api-docs
    default-consumes-media-type: application/json
    default-produces-media-type: application/json
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
    anbrain.qa.rococo.config.SecurityConfigLocal: TRACE
    anbrain.qa.rococo.controller: INFO
    anbrain.qa.rococo.service.api: INFO
    net.devh.boot.grpc: INFO
    org.springframework.boot.autoconfigure: INFO

---
spring:
  config:
    activate:
      on-profile: 'local'
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: 'http://127.0.0.1:9000'
grpc:
  client:
    rococo-userdata:
      address: static://localhost:9090
      enable-keep-alive: true
      negotiation-type: plaintext
    rococo-artist:
      address: static://localhost:9091
      enable-keep-alive: true
      negotiation-type: plaintext
    rococo-museum:
      address: static://localhost:9093
      enable-keep-alive: true
      negotiation-type: plaintext
    rococo-painting:
      address: static://localhost:9094
      enable-keep-alive: true
      negotiation-type: plaintext

rococo-front:
  base-uri: 'http://127.0.0.1:3000'
---
spring:
  config:
    activate:
      on-profile: 'docker'
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: 'http://auth.rococo.dc:9000'
grpc:
  client:
    rococo-userdata:
      address: static://userdata.rococo.dc:9090
      enable-keep-alive: true
      negotiation-type: plaintext
    rococo-artist:
      address: static://artist.rococo.dc:9091
      enable-keep-alive: true
      negotiation-type: plaintext
    rococo-museum:
      address: static://museum.rococo.dc:9093
      enable-keep-alive: true
      negotiation-type: plaintext
    rococo-painting:
      address: static://painting.rococo.dc:9094
      enable-keep-alive: true
      negotiation-type: plaintext

rococo-front:
  base-uri: 'http://frontend.rococo.dc'