server:
  port: 8080

spring:
  application:
    name: rococo-gateway
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
    disable-swagger-default-url: true
    api-docs:
      path: /v3/api-docs
    default-consumes-media-type: application/json
    default-produces-media-type: application/json
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    anbrain.qa.rococo.config.SecurityConfigLocal: TRACE
    anbrain.qa.rococo.controller: DEBUG
    anbrain.qa.rococo.service.api: DEBUG

---
spring:
  config:
    activate:
      on-profile: 'local'
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: 'http://127.0.0.1:9000'

rococo-front:
  base-uri: 'http://127.0.0.1:3000'

grpc:
  client:
    userdata-service:
      address: static://localhost:9090  # Адрес rococo-userdata
      enable-keep-alive: true
      negotiation-type: plaintext
